name: nmr_assign_state_for_shiftx2
channels:
  - omnia
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - python=3.5
  - shiftx2
  - ipykernel
  - mdtraj
  - tqdm
  - jupyterlab
  - mdanalysis
