name: nmr_assign_state_gpu 
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - mdanalysis
  - nglview=2.7.7
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8.5
  - scipy
  - seaborn
  - tqdm
  - ipykernel
  - gspread
  - pymc3
  - pip:
    - gmxapi==0.2.0a1
    - ipympl
    - mdtraj
    - scikit-cuda
    - pycuda
