name: nmr_assign_state
# This has gpu support
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - mdanalysis
  - nglview=2.7.7
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8.5
  - scipy
  - seaborn
  - tqdm
  - ipykernel
  - gspread
  - pymc3
  - ipympl
  - pip:
    - gmxapi==0.2.0a1
    - mdtraj
    - cellbell
    # - scikit-cuda
    # - pycuda
    #    export PATH=$PATH:/usr/local/cuda-10.0/bin
 #   export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda-10.0/lib64
 # ipython kernel install --user --name=nmr_assign_state
